// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RiderIssue.Api.Data;

namespace RiderIssue.Api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190730153827_Tickets")]
    partial class Tickets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RiderIssue.Api.Data.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("EventName")
                        .HasColumnName("event_name");

                    b.Property<bool>("Expired")
                        .HasColumnName("expired");

                    b.Property<string>("Number")
                        .HasColumnName("number");

                    b.Property<decimal>("Roubles")
                        .HasColumnName("roubles");

                    b.HasKey("Id");

                    b.ToTable("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
